[project]
name = "dlfs-6"
version = "0.1.0"
description = "Study code for Deep Learning from Scratch 6"
readme = "README.md"
authors = [
    { name = "jojongguk", email = "rusad96@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "regex>=2026.9.3",
    "tqdm>=4.70.0",
]

[tool.uv]
package = false
